cargo-features = ["edition2021"]

[package]
name = "Jinn"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "Jinn-sdk"
repository = "https://github.com/jinnnetwork/Jinn"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
